#!/usr/bin/env bash

# Search for neovim, fallback to vim
if which nvim >/dev/null; then
  export VISUAL="nvim"
elif which vim >/dev/null; then
  export VISUAL="vim"
else
  export VISUAL="vi"
fi

# alias febox="ssh febox"
alias febox="ssh nspawn"
alias nspawn="ssh nspawn"
alias sandbox="ssh sandbox"

export EDITOR="$VISUAL"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
fi

# Just use one editor
# alias nvim="$EDITOR"
alias vim="$EDITOR"
alias vi="$EDITOR"
alias bim="$EDITOR"
alias edit="$EDITOR"

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"

#utilities
alias rf="rm -rf"
alias lgrep="l | grep -i"
alias lagrep="la | grep"
alias gpg-start="gpgconf --launch gpg-agent"
alias lzd='lazydocker'

#docker
#alias rmdockcontainers="docker rm `docker ps -aq`"
#alias rmdockimages="docker rmi `docker images -a -q`"

#git
alias pulldev="g dev && g pull origin develop && gco -"
alias g="git"
alias gg="git grep -i"
alias gs="g s"
alias ga="g add"
alias gaa="g add -A"
alias gaoops="gaa && goops"
alias gap="g add -p"
alias gp="g pull";
alias gco="g checkout"
alias gconf="vim ~/.gitconfig"
alias gn="g new"
alias gdelbranches="git branch --merged | egrep -v \"(^\*|master|dev)\""
alias greb="git fetch && git rebase origin/master"
alias gmp="git master && git pull"
alias gfiles="gs | awk '{ print \$2 }'"

#npm
alias nr="npm run"
alias nrb="npm run build"
alias nrs="npm run start"
alias start="npm run start"
alias lscripts="jq .scripts package.json"

# Shortcuts
alias aliases="vim ~/.aliases && source ~/.aliases"
alias gitconf="vim ~/.gitconfig"
alias tmuxconf="vim ~/.tmux.conf && tmux source-file ~/.tmux.conf"
alias functions="vim ~/.functions && source ~/.functions"
alias conf="vim ~/.zshrc && source ~/.zshrc"

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
	export LS_COLORS='no=00:fi=00:di=01;31:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'
else # macOS `ls`
	colorflag="-G"
	export LSCOLORS='BxBxhxDxfxhxhxhxhxcxcx'
fi
# Always use color output for `ls`
alias ls="command ls ${colorflag}"

# List files and directories colorized in long format
alias l="ls -lF ${colorflag}"
alias la="ls -laF ${colorflag}"
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Enable aliases to be sudo’ed
alias sudo='sudo '

# IP addresses
alias ip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Show active network interfaces
alias ifactive="ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*status: active'"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache && killall -HUP mDNSResponder"

# macOS has no `md5sum`, so use `md5` as a fallback
command -v md5sum > /dev/null || alias md5sum="md5"

# macOS has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum > /dev/null || alias sha1sum="shasum"

# Trim new lines and copy to clipboard
alias c="tr -d '\n' | pbcopy"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
	alias "$method"="lwp-request -m '$method'"
done

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Edit hosts file
alias hosts="sudo vim /etc/hosts"
