#!/usr/bin/env bash

# GIT ALIASES

# new branch
nb () {
  local branchName=$1
  git new "${branchName/ze\//}"
}
# open PR - https://github.com/caarlos0/zsh-open-pr/blob/master/git-open-pr.sh
_get_git_repo() {
  echo "$1" | sed -e "s/.git$//" -e "s/.*github.com[:/]\(.*\)/\1/"
}

_build_github_pr_url() {
  # shellcheck disable=SC2039
  local upstream origin branch repo pr_url target
  upstream="$(git config --get remote.upstream.url)"
  origin="$(git config --get remote.origin.url)"
  branch="$(git symbolic-ref --short HEAD)"
  repo="$(_get_git_repo "$origin")"
  pr_url="https://github.com/$repo/pull/new"
  target="$1"
  # test -z "$target" && target=$(git for-each-ref --format='%(upstream:short)' "$(git symbolic-ref -q HEAD)" | cut -d '/' -f 2)
  test -z "$target" && target="master"
  if [ -z "$upstream" ]; then
    echo "$pr_url/$target...$branch"
  else
    # shellcheck disable=SC2039
    local origin_name upstream_name
    origin_name="$(echo "$repo" | cut -f1 -d'/')"
    upstream_name="$(_get_git_repo "$upstream" | cut -f1 -d'/')"
    echo "$pr_url/$upstream_name:$target...$origin_name:$branch"
  fi
}

# shellcheck disable=SC2039
open-pr() {
  # shellcheck disable=SC2039
  local url
  url="$(_build_github_pr_url "$*")"
  if [ "$(uname -s)" = "Darwin" ]; then
    open "$url" 2> /dev/null
  else
    xdg-open "$url" > /dev/null 2> /dev/null
  fi
}

# git clone and npm i
function cai {
  local gitRepo=$1;
  # get the last token by splitter / and strip the 4 last chars
  local repoName=${${gitRepo##*\/}%????};

  git clone $gitRepo $repoName && cd $_ && npm i;
}

# git add all and commit
function gac {
	gaa
	gcom "$@";
	gs;
}
#git commit - adds branch automatically an no quotes needed
function gc {
	local branch="[$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')]";
	if [ $branch = "[master]" ]
	then
		branch=""
	fi

	local skipVerify=false
	if [ $1 = "-n" ]
	then
		skipVerify=true
		shift
	fi

	local commitMsg="$@";

	if [ "$skipVerify" = "true" ]
	then
		g commit -m "${branch} ${commitMsg}" --no-verify;
	else
		g commit -m "${branch} ${commitMsg}";
	fi
	gs;
}

function gcom {
	local skipVerify=false
	if [ $1 = "-n" ]
	then
		skipVerify=true
		shift
	fi

	local commitMsg="$@";

	if [ "$skipVerify" = "true" ]
	then
		g commit -m "${commitMsg}" --no-verify;
	else
		g commit -m "${commitMsg}";
	fi
	gs;
}

#git commit amend
function goops {
	git commit -a --amend;
	gs;
}
#git checkout into branch. if the branch exists checkout without -b, otherwise, create it
function chout {
	if [ $1 = "-" ]
	then
		git checkout -;
	else
		local branches=$(git branches | grep $1 | wc -l);

		git checkout $([ $branches -gt 0 ] && echo '' || echo '-b') "$1";
	fi
}

# git push force with lease
function gpf() {
	local branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p');
	local skipVerify=false
	if [ $# -gt 0 ] && [ $1 = "-n" ]
	then
		skipVerify=true
		shift
	fi

	if [ "$skipVerify" = "true" ]
	then
	git push --no-verify --force-with-lease "$@" origin ${branch};
	else
	git push --force-with-lease "$@" origin ${branch};
	fi
}

#git push normal
function gpn() {
	local branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p');
	local skipVerify=false
	if [ $# -gt 0 ] && [ $1 = "-n" ]
	then
		skipVerify=true
		shift
	fi

	if [ "$skipVerify" = "true" ]
	then
	git push --no-verify "$@" origin ${branch};
	else
	git push "$@" origin ${branch};
	fi
}

# alias code to code-insiders and default to open current dir if no params
function code {
	if [ $1 ]
	then
		code-insiders "$@";
	else
		code-insiders .;
	fi
}

# Create a new directory and enter it
function mkd() {
	mkdir -p "$@" && cd "$_";
}

#npm specific
function nbin() {
	if [ -d ./node_modules/.bin ]; then
		local app="$1"
		shift
		(exec "./node_modules/.bin/${app}" "$@")
	else
		echo "Err: Not in node.js project folder.";
	fi;
}

# Change working directory to the top-most Finder window location
function cdf() { # short for `cdfinder`
	cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')";
}

# Create a .tar.gz archive, using `zopfli`, `pigz` or `gzip` for compression
function targz() {
	local tmpFile="${@%/}.tar";
	tar -cvf "${tmpFile}" --exclude=".DS_Store" "${@}" || return 1;

	size=$(
		stat -f"%z" "${tmpFile}" 2> /dev/null; # macOS `stat`
		stat -c"%s" "${tmpFile}" 2> /dev/null;  # GNU `stat`
	);

	local cmd="";
	if (( size < 52428800 )) && hash zopfli 2> /dev/null; then
		# the .tar file is smaller than 50 MB and Zopfli is available; use it
		cmd="zopfli";
	else
		if hash pigz 2> /dev/null; then
			cmd="pigz";
		else
			cmd="gzip";
		fi;
	fi;

	echo "Compressing .tar ($((size / 1000)) kB) using \`${cmd}\`…";
	"${cmd}" -v "${tmpFile}" || return 1;
	[ -f "${tmpFile}" ] && rm "${tmpFile}";

	zippedSize=$(
		stat -f"%z" "${tmpFile}.gz" 2> /dev/null; # macOS `stat`
		stat -c"%s" "${tmpFile}.gz" 2> /dev/null; # GNU `stat`
	);

	echo "${tmpFile}.gz ($((zippedSize / 1000)) kB) created successfully.";
}

# Determine size of a file or total size of a directory
function fs() {
	if du -b /dev/null > /dev/null 2>&1; then
		local arg=-sbh;
	else
		local arg=-sh;
	fi
	if [[ -n "$@" ]]; then
		du $arg -- "$@";
	else
		du $arg .[^.]* ./*;
	fi;
}

# Use Git’s colored diff when available
#hash git &>/dev/null;
#if [ $? -eq 0 ]; then
#	function diff() {
#		git diff --no-index --color-words "$@";
#	}
#fi;

# Create a data URL from a file
function dataurl() {
	local mimeType=$(file -b --mime-type "$1");
	if [[ $mimeType == text/* ]]; then
		mimeType="${mimeType};charset=utf-8";
	fi
	echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')";
}

# Start an HTTP server from a directory, optionally specifying the port
function server() {
	local port="${1:-8000}";
	sleep 1 && open "http://localhost:${port}/" &
	# Set the default Content-Type to `text/plain` instead of `application/octet-stream`
	# And serve everything as UTF-8 (although not technically correct, this doesn’t break anything for binary files)
	python -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = "text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' "$port";
}

# Compare original and gzipped file size
function gz() {
	local origsize=$(wc -c < "$1");
	local gzipsize=$(gzip -c "$1" | wc -c);
	local ratio=$(echo "$gzipsize * 100 / $origsize" | bc -l);
	printf "orig: %d bytes\n" "$origsize";
	printf "gzip: %d bytes (%2.2f%%)\n" "$gzipsize" "$ratio";
}

# Syntax-highlight JSON strings or files
# Usage: `json '{"foo":42}'` or `echo '{"foo":42}' | json`
function json() {
	if [ -t 0 ]; then # argument
		python -mjson.tool <<< "$*" | pygmentize -l javascript;
	else # pipe
		python -mjson.tool | pygmentize -l javascript;
	fi;
}

# Run `dig` and display the most useful info
function digga() {
	dig +nocmd "$1" any +multiline +noall +answer;
}

# UTF-8-encode a string of Unicode symbols
function escape() {
	printf "\\\x%s" $(printf "$@" | xxd -p -c1 -u);
	# print a newline unless we’re piping the output to another program
	if [ -t 1 ]; then
		echo ""; # newline
	fi;
}

# Decode \x{ABCD}-style Unicode escape sequences
function unidecode() {
	perl -e "binmode(STDOUT, ':utf8'); print \"$@\"";
	# print a newline unless we’re piping the output to another program
	if [ -t 1 ]; then
		echo ""; # newline
	fi;
}

# Get a character’s Unicode code point
function codepoint() {
	perl -e "use utf8; print sprintf('U+%04X', ord(\"$@\"))";
	# print a newline unless we’re piping the output to another program
	if [ -t 1 ]; then
		echo ""; # newline
	fi;
}

# Show all the names (CNs and SANs) listed in the SSL certificate
# for a given domain
function getcertnames() {
	if [ -z "${1}" ]; then
		echo "ERROR: No domain specified.";
		return 1;
	fi;

	local domain="${1}";
	echo "Testing ${domain}…";
	echo ""; # newline

	local tmp=$(echo -e "GET / HTTP/1.0\nEOT" \
		| openssl s_client -connect "${domain}:443" -servername "${domain}" 2>&1);

	if [[ "${tmp}" = *"-----BEGIN CERTIFICATE-----"* ]]; then
		local certText=$(echo "${tmp}" \
			| openssl x509 -text -certopt "no_aux, no_header, no_issuer, no_pubkey, \
			no_serial, no_sigdump, no_signame, no_validity, no_version");
		echo "Common Name:";
		echo ""; # newline
		echo "${certText}" | grep "Subject:" | sed -e "s/^.*CN=//" | sed -e "s/\/emailAddress=.*//";
		echo ""; # newline
		echo "Subject Alternative Name(s):";
		echo ""; # newline
		echo "${certText}" | grep -A 1 "Subject Alternative Name:" \
			| sed -e "2s/DNS://g" -e "s/ //g" | tr "," "\n" | tail -n +2;
		return 0;
	else
		echo "ERROR: Certificate not found.";
		return 1;
	fi;
}

# `v` with no arguments opens the current directory in Vim, otherwise opens the
# given location
function v() {
	if [ $# -eq 0 ]; then
		vim .;
	else
		vim "$@";
	fi;
}

# `o` with no arguments opens the current directory, otherwise opens the given
# location
function o() {
	if [ $# -eq 0 ]; then
		open .;
	else
		open "$@";
	fi;
}

# `tre` is a shorthand for `tree` with hidden files and color enabled, ignoring
# the `.git` directory, listing directories first. The output gets piped into
# `less` with options to preserve color and line numbers, unless the output is
# small enough for one screen.
function tre() {
	tree -aC -I '.git|node_modules|bower_components' --dirsfirst "$@" | less -FRNX;
}
